<?xml version="1.0" ?>
<robot name="drone" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find drone_ignition_bringup)/urdf/common_properties.urdf.xacro"/>
  <xacro:include filename="$(find drone_ignition_bringup)/urdf/drone.gazebo.xacro"/>
  <xacro:include filename="$(find drone_ignition_bringup)/urdf/proparm.urdf.xacro"/>

  <xacro:property name="r200_cam_rgb_px" value="0.005"/>
  <xacro:property name="r200_cam_rgb_py" value="0.018"/>
  <xacro:property name="r200_cam_rgb_pz" value="0.013"/>
  <xacro:property name="r200_cam_depth_offset" value="0.01"/>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 -0 0"/>
      <geometry>
        <mesh filename="file://$(find drone_ignition_bringup)/urdf/meshes/x4.dae"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <visual name="base_link_inertia_visual">
      <origin xyz="0 0 0" rpy="0 -0 0"/>
      <geometry>
        <mesh filename="file://$(find drone_ignition_bringup)/urdf/meshes/x4.dae"/>
      </geometry>
      <material name="black"/>
    </visual>
    <visual name="marker_visual_1">
      <origin xyz="-0.1 0 0.077" rpy="0 -0.1 0"/>
      <geometry>
        <mesh filename="file://$(find drone_ignition_bringup)/urdf/meshes/led.dae" scale= "1 1 1"/>
      </geometry>
      <material name="black"/>
    </visual>
    <visual name="marker_visual_2">
      <origin xyz="-0.09 0.059 0.059" rpy="-0.785397 -0 0.2"/>
      <geometry>
        <mesh filename="file://$(find drone_ignition_bringup)/urdf/meshes/led.dae" scale= "1 1 1"/>
      </geometry>
    </visual>
    <visual name="marker_visual_3">
      <origin xyz="-0.09 -0.059 0.059" rpy="0.785397 -0 0.2"/>
      <geometry>
        <mesh filename="file://$(find drone_ignition_bringup)/urdf/meshes/led.dae" scale= "1 1 1"/>
      </geometry>
      <material name="black"/>
    </visual>
    <visual name="downward_flashlight_visual">
      <origin xyz="-0.043704 0 0.102914" rpy="-0.2 0.000158 -1.57002"/>
      <geometry>
        <mesh filename="file://$(find drone_ignition_bringup)/urdf/meshes/spotlight.dae" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="black"/>
    </visual>
    <visual name="left_flashlight_visual">
      <origin xyz="-0.071985 0.090826 0.066102" rpy="0.06 -4.8e-05 -1.27"/>
      <geometry>
        <mesh filename="file://$(find drone_ignition_bringup)/urdf/meshes/spotlight.dae" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="black"/>
    </visual>
    <visual name="right_flashlight_visual">
      <origin xyz="-0.071985 -0.090826 0.066102" rpy="0.06 -4.8e-05 -1.87"/>
      <geometry>
        <mesh filename="file://$(find drone_ignition_bringup)/urdf/meshes/spotlight.dae" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="black"/>
    </visual>


    <collision name="base_link_inertia_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 0.3 0.25"/>
      </geometry>
    </collision>

    
    <inertial>
      <origin xyz="0 0 0.062329" rpy="0 0 0"/>
      <mass value="3.47"/>
      <inertia ixx="0.075" ixy="-0" ixz="-0"
               iyy="0.075" iyz="-0"
               izz="0.148916" />
    </inertial>
  </link>

  <!-- Wheels -->
  <xacro:wheel wheel_id="front_left" x_pos="0.256" y_pos="${wheel_separation/2}"/>
  <xacro:wheel wheel_id="front_right" x_pos="0.256" y_pos="-${wheel_separation/2}"/>
  <xacro:wheel wheel_id="rear_left" x_pos="-0.256" y_pos="${wheel_separation/2}"/>
  <xacro:wheel wheel_id="rear_right" x_pos="-0.256" y_pos="-${wheel_separation/2}"/>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="0 0 0.68" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.04" radius="0.09"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <inertial>
      <mass value="0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="0.45 0.0 0.25" rpy="0 0 0"/> <!-- 0.5 0.0 0.9 -->
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <visual>
     <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.08 0.05"/>
      </geometry>
      <material name="dark"/>
    </visual>
    <visual>
     <origin xyz="0.015 0 0" rpy="0 1.57 0"/>
      <geometry>
        <cylinder length="0.03" radius="0.02"/>
      </geometry>
      <material name="dark"/>
    </visual>
  </link>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/>

  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_depth_frame"/>
  </joint>
  <link name="camera_depth_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_depth_frame"/>
    <child link="camera_depth_optical_frame"/>
  </joint>
  <link name="camera_depth_optical_frame"/>

</robot>